### ISSUE TITLE
jsVectorMap is not defined

### ISSUE THREAD

**Issue by pwnz22** [themustafaomar/vuevectormap#11]
Hi all!

I have some issues to use this plugin with Nuxtjs 2.15.7

<img width="806" alt="image" src="https://user-images.githubusercontent.com/13133678/142773669-b08bbaa3-2881-4e31-abbd-67dc868eedbf.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/13133678/142773836-e58ac4d7-e79e-4c60-bdd1-f5a3874fa329.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/13133678/142773848-b05ad674-5759-4518-8c63-935e568131aa.png">

<img width="614" alt="image" src="https://user-images.githubusercontent.com/13133678/142773863-851d6641-4f17-4957-9200-f05674899265.png">

**Comment by pwnz22** [comment]
I did a workaround for now to get it working:
```
import Vue from 'vue';
import VueVectorMap from 'vuevectormap';
import 'vuevectormap/src/scss/vuevectormap.scss';

import jsVectorMap from 'jsvectormap';
window.jsVectorMap = jsVectorMap;

require('jsvectormap/dist/maps/world');

Vue.use(VueVectorMap);
```

**Comment by themustafaomar** [comment]
That's exactly how it should be done, but it's not need anymore as this is done internally now, and sorry for the late response 🌜
