### ISSUE TITLE
Can't set focusOn region to 'US'

### ISSUE THREAD

**Issue by hotlines-studio** [themustafaomar/vuevectormap#24]
Hi there!

I'm using the 'world' map and can use focusOn to set the region to 'EG' (Egypt), or 'AU' (Australia), 'CA' (Canada) and so on, but when I use 'US' for the United States, it just shows the entire world map. Is there another code I should be using?

Thanks!

**Comment by themustafaomar** [comment]
Hi @hotlines-studio

Sorry for the very late response please take a look at the following issues:

https://github.com/themustafaomar/jsvectormap/issues/143

https://github.com/themustafaomar/jsvectormap/issues/129
