### ISSUE TITLE
Failed to resolve entry for package "jsvectormap"

### ISSUE THREAD

**Issue by MrJibus** [themustafaomar/vuevectormap#28]
Using vuejs 3 after installing the plugin :
`
Error: Failed to resolve entry for package "jsvectormap". The package may have incorrect main/module/exports specified in its package.json.`

Is the vuejs wrapper still maintained ?

**Comment by mathieu-ducrot** [comment]
Same issue with the following error :

 WAIT  Compiling...                                                                                                                                                                                                     
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                 
 error  in ./node_modules/vuevectormap/dist/js/vuevectormap.min.js                                                                                                                                                      
Module not found: Error: Default condition should be last one

**Comment by themustafaomar** [comment]
Hi guys, sorry for the late response.

Yes it still maintained, I've just applied some important changes:

- Support es modules and commonJS instead of just the UMD.
- Cleaned up the structure of the wrapper component.
- Published a new version v2.1.1.

Thanks!

**Comment by themustafaomar** [comment]
Here is an example with Vite: https://stackblitz.com/edit/vuevectormap
