### ISSUE TITLE
@regionTooltipShow event not triggering

### ISSUE THREAD

**Issue by TheRealMattLear** [themustafaomar/vuevectormap#9]
HI! 

Thanks for providing this awesome package.

I'm having trouble triggering the regionTooltipShow event, @loaded="handleEvent" works fine but @regionTooltipShow="handleEvent" does not seem to trigger.

I've only made a simple change the codepen example to add alert and uncomment the console.log:
https://codepen.io/therealmattlear/pen/NWvxwjK

**Comment by themustafaomar** [comment]
This is a bit strange but Vue somehow when working on an HTML page, it's converting the listeners' keys to lowercase unlike when working with Vue CLI, which keeps the string as it is.

### When working with an HTML page.

![image](https://user-images.githubusercontent.com/46113191/137583783-76a7cf7a-656a-474c-88c0-a17ad98ad060.png)

### With CLI.

![image](https://user-images.githubusercontent.com/46113191/137583900-e4cffcdc-5141-4bb7-8a86-ccdafec49ec7.png)

If you're working with CLI you won't see this issue happening.

However, I'll see what I can do about the native HTML issue.

**Comment by TheRealMattLear** [comment]
Hey mate, yeah i managed to move into CLI for the time being and its working :) I've hit another snag but i'll post another issue!
